ingress-nginx:
  tcp:
    5432: "postgresql-homelab-prod/postgresql-homelab-prod:5432"

  controller:
    replicaCount: 3

    resources:
      requests:
        cpu: 100m
        memory: 128Mi

      limits:
        cpu: 300m
        memory: 256Mi