apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: tempo
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    argocd.argoproj.io/sync-options: Replace=true

spec:
  ingressClassName: "nginx"
  rules:
  - host: tempo.k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "tempo.fullname" . | default .Release.Namespace }}-query-frontend
            port: { number: 3100 }