apiVersion: v2
name: prometheus-stack-wrapper
description: A Helm Chart for Prometheus GitOps
type: application
version: 0.1.0

dependencies:
  # values 第一層 Key 必須與此 name 一致，才能正確套用 values 設定
  - name: prometheus-stack
    version: 78.5.0
    repository: https://prometheus-community.github.io/helm-charts