# ansible/playbooks/deploy_k3s.yml

---
- name: Install K3s Server
  hosts: nodes[0]
  become: yes
  tasks:
    - name: Install K3s on First Node
      shell: curl -sfL [https://get.k3s.io](https://get.k3s.io) | sh -s - server --cluster-init
    - name: Get Node Token
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token

- name: Install K3s Agents
  hosts: nodes[1:]
  become: yes
  vars:
    server_ip: "{{ hostvars[groups['nodes'][0]]['ansible_host'] }}"
    token: "{{ hostvars[groups['nodes'][0]]['k3s_token']['stdout'] }}"
  tasks:
    - name: Join Cluster
      shell: "curl -sfL [https://get.k3s.io](https://get.k3s.io) | K3S_URL=https://{{ server_ip }}:6443 K3S_TOKEN={{ token }} sh - agent"