# ansible/playbooks/init_nodes.yml

---
- name: Prepare Nodes
  hosts: nodes
  become: yes
  tasks:
    - name: Disable Swap (K8s requirement)
      shell: |
        swapoff -a
        sed -i '/swap/d' /etc/fstab

    - name: Enable IPv4 Forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present