apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # projects
  - projects/databases.yaml
  - projects/observability.yaml
  - projects/pg-apps.yaml
  - projects/platform.yaml
  - projects/security.yaml
  - projects/storage.yaml

  # applications
  - applications/databases/postgresql-appset.yaml

  - applications/observability/grafana-appset.yaml
  - applications/observability/loki-appset.yaml
  - applications/observability/prometheus-stack-appset.yaml
  - applications/observability/promtail-appset.yaml
  - applications/observability/tempo-appset.yaml

  - applications/pg-apps/cp-appset.yaml
  - applications/pg-apps/inst-appset.yaml

  - applications/platform/ingress-nginx-appset.yaml
  - applications/platform/registry-appset.yaml
#  - applications/platform/harbor-appset.yaml

#  - applications/security/vault-appset.yaml

  - applications/storage/nfs-storage-appset.yaml

