apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
    kubernetes.io/change-cause: "Deploying version || image: {{ .Values.inst.image.tag }} || APP_ENV: {{ .Values.inst.env.APP_ENV }}"

spec:
  replicas: {{ .Values.inst.replicaCount | default 1 }}
  strategy:
    # 關鍵：先殺後建，防止單一實例邏輯衝突
    type: Recreate

  selector:
    matchLabels:
      app: pg-python-inst

  template:
    metadata:
      labels:
        app: pg-python-inst

    spec:
      # TODO 節點掛了盡快飄移去別的健康節點 ; 預設 5 min 緩衝才動作
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10

      containers:
      - name: pg-python-inst
        image: "{{ .Values.inst.image.repository }}:{{ .Values.inst.image.tag }}"
        # 強迫每次都拿最新打包的 image
        imagePullPolicy: Always
        command: ["python", "src/core/v2/inst/main.py"]

        env:
        {{- range $key, $val := .Values.inst.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}

{{/*        {{- if .Values.inst.secrets }}*/}}
{{/*        - name: POSTGRES_PWD*/}}
{{/*          valueFrom:*/}}
{{/*            secretKeyRef:*/}}
{{/*              name: {{ .Values.inst.secrets.existingSecretName }}*/}}
{{/*              key: {{ .Values.inst.secrets.dbPasswordKey }}*/}}
{{/*        {{- end }}*/}}

        # volumeMounts 必須在 containers 底下
        volumeMounts:
          {{- range .Values.inst.volumesSettings }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
          {{- end }}

        resources:
          {{- toYaml .Values.inst.resources | nindent 10 }}

        # 健康檢查工具 1 ( 非必要 ) => 因為已有 livenessProbe 多它造成多餘 I/O
        # 檢查失敗時的動作: 把這個 Pod 從 Service 的 Endpoints 中剔除。停止發送網路流量給它，但絕對不會重啟 Pod
        # 【 就緒檢查 】 只在剛啟動時有用：確保檔案建好後，才顯示 READY 1/1
{{/*        readinessProbe:*/}}
{{/*          exec:*/}}
{{/*            command:*/}}
{{/*            - cat*/}}
{{/*            - /app/data/heartbeat.txt*/}}
{{/*          initialDelaySeconds: 3  # 容器啟動後 3 秒才開始檢查*/}}
{{/*          periodSeconds: 3        # 每 3 秒檢查一次*/}}

        # 健康檢查工具 2
        # 檢查失敗時的動作: 直接重啟容器（Restart Container） 強迫程式滿血復活
        # 【 存活檢查 】 驅動重啟的核心：initialDelaySeconds 必須比 readiness 大，給它緩衝
        # ─── 實施 Kafka 連動的 Liveness Exec Recovery ───
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                if [ ! -f /app/tmp/heartbeat.txt ]; then exit 1; fi
          initialDelaySeconds: 15   # 容器啟動後 10 秒才開始檢查
          periodSeconds: 3          # 每 3 秒進容器 cat 一次
          timeoutSeconds: 2         # 指令執行超時時間
          failureThreshold: 2       # 連續 2 次失敗（約 6 秒）就重啟 Pod

      # volumes 必須跟 containers 平級（在 spec 底下）
      volumes:
        {{- range .Values.inst.volumesSettings }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .claimName }}
        {{- end }}

      # 節點調度配置動態化
      {{- with .Values.inst.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.inst.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}