k9s:
  cluster: default
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - kube-system
      - argocd
      - portainer
      - databases-homelab-test
      - observability-homelab-test
      - pg-apps-homelab-test
      - platform-homelab-test
#      - security-homelab-test
#      - storage-homelab-test
#      - other-homelab-test
  view:
    active: v1/pods all
  featureGates:
    nodeShell: false
  proxy: null
