cp:
  replicaCount: 1

  image:
    repository: docker-registry.k8s.local/pg-python-cp
    pullPolicy: IfNotPresent
#    tag: "latest"
#    tag: "v1"
    tag: "v2"


  # 預設環境變數（非敏感資訊）
  # compose 服務透過 ip addr show eth0 查出IP => 172.28.113.34
  env:
    APP_ENV: "TEST"
    IS_KUBERNETES: "true"
    YAML_VERSION: "v2"

#    LOGSTASH_HOST: "172.28.113.34"
#    LOGSTASH_PORT: "5000"
#    LOKI_HOST: "172.28.113.34"
#    LOKI_PORT: "3100"

    MQTT_HOST: "172.28.113.34"
    MQTT_PORT: "1883"
    MQTT_USER: "admin"
    MQTT_PWD: "123456789"

    POSTGRES_HOST: "postgresql-homelab-test.databases-homelab-test.svc.cluster.local"
    POSTGRES_PORT: "5432"
    POSTGRES_DATABASE: "pgdatabase"
    POSTGRES_USER: "oltp_user"
    POSTGRES_PWD: "oltp_pwd"

  nodeSelector:
    workload-class: stateful

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload-class
                operator: In
                values:
                  - stateful

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"


  # 敏感資訊連動 Secret 或 SealedSecret 名稱
#  secrets:
#    existingSecretName: "postgresql-credentials"
#    dbPasswordKey: "postgres-password"

  # postgresql 明確指定非 root 的 UID
#  containerSecurityContext:
#    enabled: true
#    runAsUser: 1001
#    runAsGroup: 1001