loki:
  loki:
    ingress:
      enabled: false

    limits_config:
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      retention_period: 168h # 預發環境保留 7 天日誌


  singleBinary:
    replicas: 1

    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi

    persistence:
      enabled: true
      size: 50Gi
      # storageClass: "local-path"
      # storageClass: "standard"