loki:
  # 限制日後寫入速度，防止測試環境壓測時把節點撐爆
  limits_config:
    ingestion_rate_mb: 2
    ingestion_burst_size_mb: 4


singleBinary:
  replicas: 1

  # 測試環境使用 HostPath 或預設的 Local Storage 即可
  persistence:
    enabled: true
    size: 10Gi
    # storageClass: "local-path" # 根據你 K3s 的 StorageClass 調整