apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: security
  # 分類關鍵: 資源建立在 argocd
  namespace: argocd
  finalizers:
    # 作用對象： 針對「專案安全外殼」本身
    # 行為： 當你嘗試刪除這個 AppProject 時，Argo CD 會檢查隸屬於這個專案的所有 Application 是否都已經死光了。如果還有 App 在運作，它會卡住不讓你刪除專案，直到你把 App 清空
    # 危險性： 很低。 它是一種保護機制，防止你誤刪了專案外殼，導致底下的 App 變成沒有安全原則的孤兒
    - resources-finalizer.argocd.argoproj.io

spec:
  sourceRepos:
    - 'http://192.168.0.15:8090/pg/infra-live.git'

  # 允許專案部署到當前叢集的任何命名空間
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  # 專案合法建立其他子應用（App-of-Apps 模式）
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'