grafana:
  namespaceOverride: "grafana-homelab-stage"

  replicas: 1
  adminPassword: stage-password

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana-stage.k8s.local

  persistence:
    enabled: true
    size: 5Gi

  # 將資源定位至 Grafana 來源設定
  datasources:
    datasources.yaml:
      apiVersion: 1

      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-stack-kube-prom-prometheus.prometheus-stack.svc.cluster.local:9090
          isDefault: true

        - name: Loki
          type: loki
          access: proxy
          #          url: http://loki-read.loki.svc.cluster.local:3100
          url: http://loki.loki.svc.cluster.local:3100
          # 明確指定內部讀取路徑的 API 根節點，繞過 Loki 5.x 讀取節點對根路徑的拒絕
          jsonData:
            httpHeaderName1: "X-Scope-OrgID"
            timeout: 15
          secureJsonData:
            # 預設無認證模式下的常規值
            httpHeaderValue1: "fake"

        - name: Tempo
          type: tempo
          access: proxy
          url: http://tempo-query-frontend.tempo.svc.cluster.local:3100
          jsonData:
            # 同步防禦 Loki 相同的 401 / no org id 潛在多租戶隔離限制
            httpHeaderName1: "X-Scope-OrgID"
            timeout: 15
          secureJsonData:
            httpHeaderValue1: "fake"
