postgresql:
  global:
    security:
      allowInsecureImages: true

  # 使用架構：預設單節點（可在特定環境覆蓋為 primary-readReplica）
  architecture: replication

  # 建議在 GitOps 中固定 Image Tag，避免自動浮動
  image:
    registry: docker.io
    # 官方已將 Image 移至 legacy 倉庫，並停止在 bitnami 倉庫提供該版本
    repository: bitnamilegacy/postgresql
#    repository: bitnami/postgresql
    tag: 17.2.0-debian-12-r2


  primary:
    pgHbaConfiguration: |-
      # TYPE  DATABASE        USER            ADDRESS                 METHOD
      local   all             all                                     trust
      host    all             all             127.0.0.1/32            md5
      host    all             all             0.0.0.0/0               md5


  # 監控最佳實踐：啟用 Prometheus Metrics Exporter
#  metrics:
#    enabled: true
#    service:
#      ports:
#        metrics: 9187
#
#    serviceMonitor:
#      enabled: true
#      interval: 30s

  # 安全最佳實踐：不使用預設的非 root 權限，明確指定 UID
  containerSecurityContext:
    enabled: true
    runAsUser: 1001

  auth:
    username: pg-user
    database: pgdatabase

    existingSecret: postgresql-credentials
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
      replicationPasswordKey: replication-password