inst:
  replicaCount: 1

  image:
    repository: docker-registry.k8s.local/pg-python-inst
    pullPolicy: IfNotPresent
#    tag: "latest"
#    tag: "v1"
    tag: "v6"


  # 預設環境變數（非敏感資訊）
  # compose 服務透過 ip addr show eth0 查出IP => 172.28.113.34
  env:
    APP_ENV: "TEST"
    IS_KUBERNETES: "true"
    YAML_VERSION: "v2"

#    LOGSTASH_HOST: "172.28.113.34"
#    LOGSTASH_PORT: "5000"
#    LOKI_HOST: "172.28.113.34"
#    LOKI_PORT: "3100"

    MQTT_HOST: "172.28.113.34"
    MQTT_PORT: "1883"
    MQTT_USER: "admin"
    MQTT_PWD: "123456789"

    POSTGRES_HOST: "postgresql-homelab-test.postgresql-homelab-test.svc.cluster.local"
    POSTGRES_PORT: "5432"
    POSTGRES_DATABASE: "pgdatabase"
    POSTGRES_USER: "oltp_user"
    POSTGRES_PWD: "oltp_pwd"

    SQLITE_DB_NAME: "./data/kafka_consumer_local.db"

    KAFKA_HOST: "172.28.113.34:9094"
    KAFKA_AUTO_OFFSET_RESET: "earliest"
    KAFKA_ENABLE_AUTO_COMMIT: "false"
    # schema-registry:8081
    KAFKA_SCHEMA_REGISTRY_HOST: "172.28.113.34:8081"

    CONSUMER_GROUP_ID: "iot-data-mach-processor"
    CONSUMER_ORDER_TOPIC: "source.cp.mach-order"

    # 需事先查清楚
    MACH_ID: "67"
    MACH_NAME: "M-CNC-30"



  # 進行 K8s Volume 掛載 => NFS 儲存機制 ( SQLite )
  volumeMounts:
    - name: sqlite-storage
      # 容器內的應用程式讀寫路徑
      mountPath: /app/data
  volumes:
    - name: sqlite-storage
      persistentVolumeClaim:
        # 對接 GitOps 產出的 PVC
        claimName: sqlite-nfs-pvc



  nodeSelector:
    workload-class: stateful

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload-class
                operator: In
                values:
                  - stateful

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"


  # 敏感資訊連動 Secret 或 SealedSecret 名稱
#  secrets:
#    existingSecretName: "postgresql-credentials"
#    dbPasswordKey: "postgres-password"

  # postgresql 明確指定非 root 的 UID
#  containerSecurityContext:
#    enabled: true
#    runAsUser: 1001
#    runAsGroup: 1001