apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: tempo
  namespace: argocd

spec:
  project: observability

  # 依賴自訂變數
  source:
    repoURL: http://192.168.0.15:8090/pg/infra-live.git
    targetRevision: main
    path: applications/observability/tracing/tempo

    helm:
      valueFiles:
        - values/common.yaml
        - values/test.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: tempo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true