prometheus:
  replicaCount: 2

  server:
    ingress:
      enabled: false

    persistentVolume:
      enabled: true
      size: 50Gi

  alertmanager:
    persistentVolume:
      enabled: true
      size: 10Gi