apiVersion: v2
name: prometheus-wrapper
description: A Helm Chart for Prometheus GitOps
type: application
version: 0.1.0
appVersion: "2026.05"

dependencies:
  # values 第一層 Key 必須與此 name 一致，才能正確套用 values 設定
  - name: prometheus
    version: 27.39.0
    repository: https://prometheus-community.github.io/helm-charts