apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: harbor-appset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: platform

spec:
  generators:
    - list:
        elements:
          - env: homelab-test
            server: https://kubernetes.default.svc
#          - env: homelab-stage
#            server: https://kubernetes.default.svc
#          - env: homelab-prod
#            server: https://kubernetes.default.svc

  template:
    metadata:
      name: 'harbor-{{env}}'

    spec:
      project: platform
      source:
        repoURL: http://192.168.0.15:8090/pg/infra-live.git
        targetRevision: main
        path: charts/platform/harbor
        helm:
          valueFiles:
            - 'values/common.yaml'
            - '../../../environments/{{env}}/harbor-values.yaml'

      destination:
        server: '{{server}}'
        namespace: 'platform-{{env}}'

      syncPolicy:
        # prune: true → 務必確保 Chart 裡的 PVC 有設定 reclaimPolicy: Retain，防止 Git 誤刪導致硬碟暴斃
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnFields=true
          - FailOnSharedResource=false
#          - Replace=true
          - PruneLast=true
          - PrunePropagationPolicy=foreground
          - RespectIgnoreDifferences=true