apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: ingress-nginx-appset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: platform

spec:
  generators:
    - list:
        elements:
          - env: homelab-test
            server: https://kubernetes.default.svc
#          - env: homelab-stage
#            server: https://kubernetes.default.svc
#          - env: homelab-prod
#            server: https://kubernetes.default.svc

  template:
    metadata:
      name: 'ingress-nginx-{{env}}'

    spec:
      project: platform
      source:
        repoURL: http://192.168.0.15:8090/pg/infra-live.git
        targetRevision: main
        path: charts/platform/ingress-nginx
        helm:
          valueFiles:
            - 'values/common.yaml'
            - '../../../environments/{{env}}/ingress-nginx-values.yaml'

      destination:
        server: '{{server}}'
        namespace: 'ingress-nginx-{{env}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnFields=true
      #      - Replace=true
      #      - PruneLast=true