apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: postgresql-appset
  namespace: argocd
  #  finalizers:
  #    # 千萬別在有狀態服務加這行，否則一不小心就會引發連鎖全面崩潰
  #    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: databases

spec:
  generators:
    - list:
        elements:
          - env: homelab-test
            server: https://kubernetes.default.svc
#          - env: homelab-stage
#            server: https://kubernetes.default.svc
#          - env: homelab-prod
#            server: https://kubernetes.default.svc

  template:
    metadata:
      name: 'postgresql-{{env}}'

    spec:
      project: databases
      source:
        repoURL: http://192.168.0.15:8090/pg/infra-live.git
        targetRevision: main
        path: charts/databases/postgresql
        helm:
          valueFiles:
            - 'values/common.yaml'
            - '../../../environments/{{env}}/postgresql-values.yaml'
      destination:
        server: '{{server}}'
        # 自動帶入命名空間，讓不同環境的互相隔離
        namespace: 'postgresql-{{env}}'

      syncPolicy:
        automated:
          # 有狀態服務關閉自動修剪(Prune)，避免手滑刪除資料
          prune: false
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      #      - Replace=true
      #      - PruneLast=true