grafana:
#  namespaceOverride: "grafana-homelab-test"
  namespaceOverride: "observability-homelab-test"

  replicas: 1
  adminPassword: test-password

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.k8s.local

  persistence:
    enabled: false

  grafana.ini:
    # 確保開啟功能 → Loki 連動 Tempo
    feature_toggles:
      enable: traceToLogs,logsToTrace

  # 將資源定位至 Grafana 來源設定
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources: # 若須手動更新進行測試 註解整塊
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-stack-homelab-t-prometheus.observability-homelab-test.svc.cluster.local:9090
          isDefault: true

        - name: Loki
          type: loki
          access: proxy
          url: http://loki-homelab-test.observability-homelab-test.svc.cluster.local:3100
          jsonData:
            httpHeaderName1: "X-Scope-OrgID"
            timeout: 15
          secureJsonData:
            # 預設無認證模式下的常規值
            httpHeaderValue1: "fake"

        - name: Tempo
          type: tempo
          access: proxy
#          url: http://tempo-homelab-test-query-frontend.observability-homelab-test.svc.cluster.local:3100
          url: http://tempo-homelab-test.observability-homelab-test.svc.cluster.local:3100
          jsonData:
            # 同步防禦 Loki 相同的 401 / no org id 潛在多租戶隔離限制
            httpHeaderName1: "X-Scope-OrgID"
            timeout: 15
          secureJsonData:
            httpHeaderValue1: "fake"