ingress-nginx:
  tcp:
    5432: "postgresql-homelab-test/postgresql-homelab-test:5432"

  controller:
    replicaCount: 1

    resources:
      requests:
        cpu: 100m
        memory: 128Mi

      limits:
        cpu: 300m
        memory: 256Mi