apiVersion: v1
kind: Secret

metadata:
  name: postgresql-credentials
type: Opaque

stringData:
  postgres-password: "postgres-password123"
  password: "pgsecretpassword"
  replication-password: "replication-password123"