apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: nfs-storage-appset
  namespace: argocd
  #  finalizers:
  #    # 千萬別在有狀態服務加這行，否則一不小心就會引發連鎖全面崩潰
  #    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: storage

spec:
  generators:
    - list:
        elements:
          - env: homelab-test
            server: https://kubernetes.default.svc
#          - env: homelab-stage
#            server: https://kubernetes.default.svc
#          - env: homelab-prod
#            server: https://kubernetes.default.svc

  template:
    metadata:
      name: 'nfs-storage-{{env}}'

    spec:
      project: storage
      source:
        repoURL: http://192.168.0.15:8090/pg/infra-live.git
        targetRevision: main
        path: charts/storage/nfs-storage
        helm:
          valueFiles:
            - 'values/common.yaml'
            - '../../../environments/{{env}}/nfs-storage-values.yaml'
      destination:
        server: '{{server}}'
        namespace: 'pg-apps-{{env}}'

      syncPolicy:
        # prune: true → 務必確保 Chart 裡的 PVC 有設定 reclaimPolicy: Retain，防止 Git 誤刪導致硬碟暴斃
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnFields=true
          - FailOnSharedResource=false
#          - Replace=true
          - PruneLast=true
          - PrunePropagationPolicy=foreground
          - RespectIgnoreDifferences=true