apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: grafana
  namespace: argocd

spec:
  project: observability

  # 依賴自訂變數
  source:
    repoURL: http://192.168.0.15:8090/pg/infra-live.git
    targetRevision: main
    path: applications/observability/visualization/grafana

    helm:
      valueFiles:
        - values/common.yaml
        - values/test.yaml

  # 不依賴自訂變數
#  source:
#    repoURL: https://grafana.github.io/helm-charts
#    chart: grafana
#    targetRevision: 9.3.0
#
#    helm:
#      values: |
#        adminPassword: admin123
#        service:
#          type: ClusterIP
#
#        ingress:
#          enabled: true
#          ingressClassName: nginx
#          hosts:
#            - grafana.k8s.local

  destination:
    server: https://kubernetes.default.svc
    namespace: grafana

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
#      - Replace=true
#      - PruneLast=true