apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: grafana
  namespace: argocd

spec:
  project: observability

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 9.3.0

#    helm:
#      valueFiles:
#        - values/common.yaml
#        - values/test.yaml
    helm:
      values: |
        adminPassword: admin123
        service:
          type: ClusterIP

  destination:
    server: https://kubernetes.default.svc
    namespace: grafana

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true