apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ .Values.storage.pvcName | default (printf "%s-nfs-pvc" .Release.Name) }}
  namespace: {{ .Release.Namespace }}

spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage.size | default "5Gi" }}
  storageClassName: {{ .Release.Name }}-nfs-storage-class