apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - visualization/grafana/app.yaml
#  - metrics/prometheus/app.yaml
  - metrics/prometheus-stack/app.yaml
#  - metrics/exporters/postgres-exporter/app.yaml
  - logging/loki/app.yaml
  - logging/promtail/app.yaml
  - tracing/tempo/app.yaml