grafana:
  replicas: 1
  adminUser: admin
  adminPassword: admin123

  global:
    image:
      tag: "10.4.1"

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.k8s.local

  nodeSelector:
    workload-class: stateless
    traffic-zone: internal-only

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload-class
                operator: In
                values:
                  - stateless
              - key: traffic-zone
                operator: In
                values:
                  - internal-only

  persistence:
    enabled: true
    size: 5Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi

    limits:
      cpu: 500m
      memory: 512Mi


# [ 位置無效 ] 關閉 Sidecar 聯帶重啟效應
#sidecar:
#  dashboards:
#    enabled: false  # 關閉儀表板動態監控
#  datasources:
#    enabled: false  # 關閉資料源動態監控，改走純靜態讀取