apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: databases
  # 分類關鍵: 資源建立在 argocd
  namespace: argocd
  finalizers:
    # 作用對象： 針對「Git 目錄結構的同步器」
    # 行為： 級聯刪除子應用。如果有人把這個 databases 母應用刪除（無論在 UI 點刪除，或是在更上層的 homelab-test-root 裡移除了這個定義）
    # 結果： Argo CD 會觸發連鎖反應，把 applications/databases/ 底下掃描出來的所有子 Application 資源從 K8s 裡抹除
    # 危險性： 中高。 如果子應用本身有保護，資料還不會死；但如果子應用沒防護，這會引發連鎖全面崩潰
    - resources-finalizer.argocd.argoproj.io

spec:
  project: databases
  source:
    repoURL: http://192.168.0.15:8090/pg/infra-live.git
    targetRevision: main
    # 大類掃描所有小類
    path: applications/databases

  destination:
    server: https://kubernetes.default.svc
    # 母應用建立在 argocd 進行全面監控
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
#      - Replace=true
#      - PruneLast=true