replicas: 1

adminUser: admin
adminPassword: admin123

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx

grafana.ini:
  server:
    root_url: http://grafana.k8s.local

persistence:
  enabled: true
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi