replicas: 1

adminUser: admin
adminPassword: admin123

service:
  type: ClusterIP

persistence:
  enabled: true
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: false