grafana:
  replicas: 1
  adminPassword: stage-password

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana-stage.k8s.local

  persistence:
    enabled: true
    size: 5Gi
