# helm/app-stack/templates/app/app-deploy.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  annotations:
    reloader.stakater.com/auto: "true" # 測試 5：配置更新自動觸發重啟 ( Reloader )
    kubernetes.io/change-cause: "Deploying version {{ .Values.image.tag }}"
spec:
  # 測試 13：零停機更新與回滾 (Rolling Update & Rollback)
{{/*  replicas: 2*/}}
{{/*  strategy:*/}}
{{/*    type: RollingUpdate*/}}
{{/*    rollingUpdate:*/}}
{{/*      maxSurge: 1       # 更新時最多可以多開幾個 Pod # 只允許一個額外的新 Pod 出現嘗試交接，所以不會有無窮無盡的新 Pod 塞爆你的節點*/}}
{{/*      maxUnavailable: 0 # 更新時最少要維持幾個 Pod 在線 # 強制要求「舊的必須都在，新的才能上」*/}}

  # 測試 16： 高可用單一實例 ( HA Singleton )
  replicas: 1
  strategy:
    type: Recreate  # 關鍵：先殺後建，防止單一實例邏輯衝突

  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      # 測試 16： 高可用單一實例 ( HA Singleton )
      affinity: # 配合節點標籤
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: service-type
                    operator: In
                    values:
                      - app

      nodeSelector:
        service-type: app # 強制 Pod => 指定標籤節點
      containers:
      - name: python-worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["python", "app.py"]

        envFrom: # ConfigMap 裡的所有 Data 直接變成環境變數
          - configMapRef:
              name: app-config

        env: # 手動一對一指定
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD

        # 測試 13： 健康檢查
          # HTTP Get：看網頁路徑是否回傳 200
          # TCP Socket：看某個 Port 有沒有開
          # [ 目前簡易腳本 ] Exec Command：在容器內執行一個指令，回傳 0 就算成功
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5 # 給 Python 啟動的一點緩衝時間
          periodSeconds: 5       # 每 5 秒檢查一次