ingress-nginx:
  controller:
    replicaCount: 1
    kind: Deployment
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet

    updateStrategy:
      type: Recreate

    service:
      type: ClusterIP
#      type: LoadBalancer
      ports:
        http: 80
        https: 443
        postgresql: 5432
      targetPorts:
        http: 80
        https: 443
        postgresql: 5432

    global:
      image:
        image: ingress-nginx/controller
        runAsNonRoot: false
        runAsUser: 0

    # 安全性權限：確保 Nginx 能綁定 80/443 等低位埠
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
          - NET_BIND_SERVICE
        drop:
          - ALL

    containerPorts:
      http: 80
      https: 443
      postgresql: 5432

    metrics:
      enabled: true

    ingressClassResource:
      default: true


    # 節點親和性 (Node Affinity) 與反親和性 (Pod Anti-Affinity)
    # 確保 Pod 部署在正確的節點，且不會與其他同類型的 Pod 發生衝突
    nodeSelector:
      workload-class: stateless
      traffic-zone: edge-ingress

#    affinity:
#      nodeAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#          nodeSelectorTerms:
#            # 若是新增多個 nodeSelectorTerm，代表條件之間是 OR 的關係
#            - matchExpressions:
#                # 條件 1
#                - key: workload-class
#                  operator: In
#                  # 設定多個值代表條件之間是 OR 的關係
#                  values:
#                    - stateless
#                # 條件 2 (代表 AND)
#                - key: traffic-zone
#                  operator: In
#                  values:
#                    - edge-ingress