{{- if .Values.registry.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Release.Name }}

  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  ingressClassName: {{ .Values.registry.ingress.className }}
  {{- if .Values.registry.ingress.tls.enabled }}

  tls:
    - hosts:
        - {{ .Values.registry.ingress.host }}
      secretName: {{ .Values.registry.ingress.tls.secretName }}

{{- end }}

  rules:
    - host: {{ .Values.registry.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.registry.service.port }}

{{- end }}