apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}

spec:
  type: {{ .Values.registry.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.registry.service.port }}
      targetPort: 5000